title: Colors
modelClass: DominicMercier\Nikeid\Models\Color
list: $/dominicmercier/nikeid/models/color/columns.yaml
recordUrl: 'dominicmercier/nikeid/colors/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
